sudo: required
language: ruby

env:
  - ANSIBLE_VERSION=2.4
  - ANSIBLE_VERSION=2.5
  - ANSIBLE_VERSION=2.6

services:
  - docker

before_install:
  - bundle install

script:
  - kitchen conv phpfpm-debian-9
  - kitchen conv phpfpm-debian-9 | grep changed=0
  - kitchen verify phpfpm-debian-9
