---
- import_tasks: base.yml
  tags: phpfpm

- import_tasks: pools.yml
  tags: phpfpm

- name: enable and start php-fpm
  systemd:
    name: php{{ phpfpm_version }}-fpm
    state: started
    enabled: yes
  tags: phpfpm
